import { Component,HostBinding} from '@angular/core';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'table';
  headers: any={
    thead:['Unique ID','Type','Shared with','Modification Date','Status','Exp Date'],
    displayed:['id','type','connect','updatedate','status','validdate']
   }
   dataSource: any =
      [{
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 20,
        'type': 'asdfasdf',
        'connect': 'asdf',
        'updatedate': 'asdfasdfasfasdfa',
        'status': '2342423423',
        'validdate': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:05',
        'modifyBy': null,
        'modifyDate': null
      }
    ]

}
